name : Deploy Terraform Infra

on: 
  push:
    branches:
      - main
    paths: 
      - 'Terraform/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.6.0 
        
      - name: Terraform init 
        run: terraform init
        working-directory: Terraform/environments/dev
        
      - name: Terraform Plan
        run: terraform plan
        working-directory: Terraform/environments/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Terraform/environments/dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
